### ISSUE TITLE
How to share my draw screen?

### ISSUE THREAD

**Issue by mcvarer** [trekhleb/okso-app#1]
I have draw some patterns and want to share my team. 
How can I do that.

**Comment by trekhleb** [comment]
Hi @mcvarer 

The collaborative feature that will allow working on the same screen by several teammates is planned ([see the Roadmap](https://feedback.okso.app/feedback)) but it is not yet ready. 

So currently you have the following options:

- Export your drawing as a (`PNG`, `SVG`, `JPG`) image and share the image with the team. See the `Menu → File → Export As → ...`
- Save your drawing to the file (with the `***.okso` extension). Then you may share the file with the team. See the `File → Save` and `File → Open` menus.
